### ISSUE TITLE
Se egne anmeldelser på fremsiden

### ISSUE THREAD

**Issue by SMadland** [Mamon-AS/Mamon#114]
I dag kan man ikke se egne anmeldelser på fremsiden. Det burde vel være mulig? 

Har fått varsel på egen anmeldelsene i bilde under, så jeg har en anmeldelse på denne brukeren, men det vises ikke på fremsiden. 

![Image](https://github.com/Mamon-AS/Mamon/assets/118986568/953b75eb-92b2-4307-b920-debf8dd80963)

**Comment by stjernando** [comment]
Det er ikke mulig pdd by design, men det kan fikses

**Comment by SMadland** [comment]
Jeg tenker det er naturlig, men åpen for at den kan legges i nice to have om det er krevende å få til

**Comment by stjernando** [comment]
Det er ikke krevende, men jeg kjenner meg ikke enig i at mine egne innlegg skal i den feeden. Jeg er jo på en måte ikke interessert i å se hva jeg selv har lagt ut. Hva tenker du?

**Comment by SMadland** [comment]
Jeg mistenker det er motsatt. At folk gjerne vil se/sjekke egne innlegg i det de har postet. Se at det ser ok ut. Følge med på likes/kommentarer osv. Folk er mer selvopptatt enn man tror.

Hvis det ikke dukker opp tror jeg mange tror at det ikke ble postet siden det er dukker opp i feeden når man poster på FB/IG/LI osv. Men ikke sikkert jeg har rett her (heller).

@msingstad Hva tenker du her?

**Comment by SMadland** [comment]
Ikke uenig det. 

Godt spørsmål - Jeg tror ikke det er negativt om egne anmeldelser vises. Er mer redd for at de som poster ikke tror det er postet fordi det ikke dukker opp i feeden.

Men jeg kan gi meg på denne, vi kan starte uten 😄 Så ser vi heller om det er ønskelig fra brukerne når flere har begynt å bruke den.
