### ISSUE TITLE
Knytte kontakt med andre brukere

### ISSUE THREAD

**Issue by SMadland** [Mamon-AS/Mamon#13]
Mulighet til å søke på andres profiler og følge de/knytte kontakt for å se mine venner's anmeldelser. 

Hele poenget med Mamon som er det som skiller oss ut fra andre som baserer seg på anmeldelser er at disse ikke er anonyme, men av personer vi kjenner. 

Jeg er ikke interessert i hva Kari på 55 mener om bil, eller Roger på 18 år. Jeg vil vite hva de rundt meg kjøper og anbefaler. Både fordi vi fort har samme "smak", men også fordi det er noe sosialt i hva de rundt meg kjøper av varer og tjenester.

**Comment by SMadland** [comment]
Akkurat 11 mnd siden denne ble laget 😄 (IKKE hinting bare så det er sagt!)

Men tenkte å høre status her? 😊

**Comment by SMadland** [comment]
@msingstad Prøver meg igjen 😄 Er veldig spent på hvordan dette gjøres og spent på å teste det. Hva er status her?

**Comment by msingstad** [comment]
Ikke noe nytt foreløpig

**Comment by SMadland** [comment]
Den er god!

Denne delen er noe av det jeg gleder meg mest til. Da er på mange måter plattformen blitt unik (så vidt jeg vet).
Derfor jeg spør en del. Skal vente en stund før jeg spør igjen, lover 🤐😄

**Comment by SMadland** [comment]
@stjernando Ser jeg har fått "to følgere" på profilen min. Så her har du også skjedd litt? Kan foreløpig ikke søke etter andre, eller finne ut hvem som følger meg slik jeg ser det?

**Comment by stjernando** [comment]
@SMadland Du kan følge folk og bli fulgt sjøl, dette var en større oppgave.
Legge til nettopp hvem som følger deg og søke etter de er en mindre oppgave. PR-en begynte å bli  ganske grotesk stor så jeg tenkte det var greit å lansere den tidlig og få feedback enn å legge til all funksjonalitet 😛

**Comment by SMadland** [comment]
@stjernando Det er jo helt rått! 

Skjønner 😄 Høres lurt ut å ta det stegvis.

**Comment by msingstad** [comment]
@stjernando ⭐️

**Comment by SMadland** [comment]
@msingstad Hyggelig å se deg her 👋👋 (ikke ironisk altså 😄)

**Comment by msingstad** [comment]
Lurker som regel rundt
