### ISSUE TITLE
Nye kommentarer kommer ikke som et nytt varsel, kun likes og nye følgere/følgeforespørsler

### ISSUE THREAD

**Issue by SMadland** [Mamon-AS/Mamon#130]
Får ikke opp varsel når noen kommenterer på innleggene mine lenger, kun likes. Se bilde. (Jeg har her kommentert mellom uten at det kommer opp)

![Image](https://github.com/Mamon-AS/Mamon/assets/118986568/55f50fc9-4ae4-4931-95b8-cbcf676d70e7)

**Comment by stjernando** [comment]
Fikses i https://github.com/Mamon-AS/Mamon/pull/131 , samme pr-en fjerner også notifikasjoner på dine egne anmeldelser.
