### ISSUE TITLE
Det er kun linken til sykkelen som fungerer. De andre er det ikke mulig å klikke på

### ISSUE THREAD

**Issue by SMadland** [Mamon-AS/Mamon#132]
Overskriften sier alt.

**Comment by stjernando** [comment]
2 minutter arbeid, men det er litt vondt å scrolle på telefonen hvis bildet også er en link 🤔

**Comment by SMadland** [comment]
Mente ikke at bilde også skulle bli en del av linken. Mente at disse linkene (se bildene) ikke fører noe sted. Man får "blå skrift" når man fører musen over, men det er ikke mulig å klikke seg inn på linken.

![image](https://github.com/Mamon-AS/Mamon/assets/118986568/ab3d80a6-57ba-45f0-b578-cb78980ede4d)
![image](https://github.com/Mamon-AS/Mamon/assets/118986568/bcc4bb29-ad38-4d09-bd83-06f0d5239138)

**Comment by stjernando** [comment]
Aha! Disse anmeldelsene ble laget før den funksjonaliteten eksisterte, så de har ikke link! :)

**Comment by SMadland** [comment]
Skjønner. Mistenkte det :) 

Var mest siden jeg får den "blå skriften" når jeg tar musen over at jeg lurte.

Men da er det all good!
