### ISSUE TITLE
Småfiks

### ISSUE THREAD

**Issue by SMadland** [Mamon-AS/Mamon#134]
Tok en liten runde på tlf for å se etter fix'es.

- [x] Likerknappen blir værende åpen selv etter jeg har klikket på en emoji, evt prøvd å klikke et sted på siden for å få den bort. Slik det er nå må man aktivt trykke på "Lik" igjen for å få den bort.
- [x] Varsler forsvinner når jeg trykker på de. De kommer tilbake når jeg F5'er siden, men er det ikke fint at varslene blir liggende hvertfall en uke? Når mitt varsel forsvant skulle jeg gjerne ha klikket på det på ny for å gå tilbake og kommentere noe mer, men da var det borte.
- [x] Jeg savner litt Mamon-logoen på mobilen, ved å skyve søkefeltet og fjæra inn mot midten. Men forstår om det ikke går. Ser bra ut med stjerna også.

**Comment by stjernando** [comment]
![image](https://github.com/Mamon-AS/Mamon/assets/44195327/18d60aed-4695-41f0-a824-77b08094f492)
![image](https://github.com/Mamon-AS/Mamon/assets/44195327/9f586557-8944-4efb-8676-38fd9a8bb6a9)

**Comment by SMadland** [comment]
Troooor kanskje jeg går for den med mindre søkefelt og en logo som ikke ser ut som et trekkspill

**Comment by stjernando** [comment]
Hva om jeg bare skjulern når søkefeltet er aktivt, @SMadland ?

**Comment by SMadland** [comment]
God ide! Tenker det går helt fint.
