### ISSUE TITLE
Bilde av den som poster anmeldelsen på selve anmeldelsen - Slik at det blir personlig

### ISSUE THREAD

**Issue by SMadland** [Mamon-AS/Mamon#54]
Henger sammen med det å knytte kontakt med andre. De må da kunne vite hvem i deres nettverk som har postet hvilken anmeldelse.

**Comment by stjernando** [comment]
Holder med navn, eller er det ekstra ønskelig med bilde?

**Comment by SMadland** [comment]
Jeg tenker nok med bilde. Det gjør det visuelt så mye bedre (og mer personlig). 

Prøvde å legge til et bilde her fra LinkedIn som eksemplifiserer det. Men det funket ikke. Sender det på Slack.

**Comment by stjernando** [comment]
fixed

**Comment by stjernando** [comment]
Vel og merke, @SMadland. Reviews som har blitt gjort før denne endringen kom på plass har ikke bilde eller navn på reviewen. Alle fremtidige reviews vil ha.
