### ISSUE TITLE
Feilmelding ved posting av anmeldelse

### ISSUE THREAD

**Issue by SMadland** [Mamon-AS/Mamon#58]
![Image](https://github.com/Mamon-AS/Mamon/assets/118986568/ce6768d9-26f1-4a99-bd41-836b2312e067)

**Comment by stjernando** [comment]
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Samme greia vi har snakket om tidligere, men jeg tror jeg kan fikse det med en liten tweak på implementeringa

**Comment by SMadland** [comment]
Stemmer. Vi har jo testa det, så ingen hast med at dette må funke med en gang. 

Tenkte jeg skulle legge den til så vi har notert det enn plass.

**Comment by stjernando** [comment]
Dette har blitt litt bedre nå
