### ISSUE TITLE
Kunne trykke på bilde av profilen og for å bli sendt direkte til profilen

### ISSUE THREAD

**Issue by SMadland** [Mamon-AS/Mamon#64]
Tenker det er gull å kunne trykke på bilde av personen som la ut bilde for å se profilen til personen. Liten sak som gjør anmeldelsen mer levende.

**Comment by stjernando** [comment]
Bare å teste @SMadland

**Comment by SMadland** [comment]
Funker fjell det! Eneste er vel at jeg ikke trykker på bilde som etterspurt over, men på navnet, men det betyr ikke så mye. Kunne du gjort det slik at navn og bilde står litt som på bilde under her. Jeg tenker vi ikke trenger at det står "Skrevet av Sondre Madland", men heller bare mitt navn og bilde nederst til høyre eller venstre. Alle skjønner at den anmeldelsen da er min. Tanker?

![image](https://github.com/Mamon-AS/Mamon/assets/118986568/79663475-8112-46ed-b71f-f6bd2b400a6f)

**Comment by stjernando** [comment]
Jeg kan pynte litt på den, og legge til link på bilde også.

**Comment by SMadland** [comment]
@stjernando Du er en legende.
