### ISSUE TITLE
Lik og kommenter anmeldelse

### ISSUE THREAD

**Issue by SMadland** [Mamon-AS/Mamon#69]
Muligheten til å "like" og kommentere anmeldelsene gjør de mer interaktive, og en god grunn til å sjekke innom plattformen.

**Comment by stjernando** [comment]
Hva tenker du her a,
- Se reaksjoner på en anmeldelse, klikker du på den så vil du også se kommentarene? @SMadland

**Comment by SMadland** [comment]
Godt spørsmål - Jeg går jo fort og ser hva andre har 😄

Men typ --> "Lik" "Kommenter" med ulike emojier når du holder over "Lik" og kanskje en eller to kommentarer som viser under kommentarer. Typ som på bilde som selvsagt er hentet fra vår alles kjære LI.

![Image](https://github.com/Mamon-AS/Mamon/assets/118986568/fed613d2-32f8-4a70-a85e-9936c9e90769)

**Comment by stjernando** [comment]
Jaja alt i orden det, så jeg er ikke eksponert for mer enn 2 kommentarer med mindre jeg skulle klikke inn på en anmeldelse, enig? @SMadland

**Comment by SMadland** [comment]
Ja, enig! Tenker det holder. Evt "Se flere kommentarer" for å slippe å klikke innpå?

**Comment by stjernando** [comment]
![Image](https://github.com/Mamon-AS/Mamon/assets/44195327/7ed7de9d-d9b2-4585-aba1-e624cf3cb499)
