### ISSUE TITLE
Kunne sjekke sitt eget nettverk

### ISSUE THREAD

**Issue by SMadland** [Mamon-AS/Mamon#71]
Fint å kunne ha en oversikt over antall venner i firkanten under profilbilde. Og gjerne at man kan trykke på den og se hvem det faktisk er. Typ Venner: 138

Under profilbilde har vi den firkanten 👇

![Image](https://github.com/Mamon-AS/Mamon/assets/118986568/3f9ea2ba-4fc4-4c44-a87e-b4f507606967)

Ser for meg vi kan ha følgende i den:
Navn - Følgere/Venner - Bio - Antall anmeldelser - (Mer som jeg ikke kommer på nå)

**Comment by stjernando** [comment]
Alt her er vel på plass bortsett fra klikke på følgere og bio? Skjønner at du vil ha en annen struktur. Det kan man fikse

**Comment by SMadland** [comment]
Ja, var mest for å tenke "hele bilde". At profilen har litt info som gjør den mer "levende" som er ordet jeg bruker om alt her 😂

Issuen er egt bare det å kunne se antall følgere/venner å kunne sjekke hvem de er.
