### ISSUE TITLE
Lage et API som sender kjøp direkte inn på Mamon

### ISSUE THREAD

**Issue by SMadland** [Mamon-AS/Mamon#72]
Jeg har tenkt en del på hvordan vi kan gjøre det lettere å ville legge inn en anmeldelse. Så kom jeg over denne saken på LI. Her er greia at når du kjøper et produkt legges det også inn på "Tings" som er en plattform for fiksing og service av produkt du kjøper. Vi har vel snakka om noe lignende før tror jeg? Altså med et slikt API.

Kunne vi laget noe av det samme? Altså et API som sender produktet rett inn på plattformen vår etter at det er kjøpt på nett som gjør at det ligger klart til å bli anmeldt neste gang du går inn på Mamon (evt når du selv vil). På den måten slipper man å stresse med å finne riktig link for å kunne anmelde. I tillegg blir det mye lettere å ha orden på våre kunder. De får ikke tilgang til APIet uten å betale. (Per nå kan alle anmelde VG.no selv om de ikke er kunde av oss).

Regner med dette er en stor og krevende oppgave, men prøver meg 😄

(Jeg kan gjerne booke møte med han Andreas i Tings for å høre hvordan de gjør det/lære om dere vil det)

![Image](https://github.com/Mamon-AS/Mamon/assets/118986568/f27a7596-a9bd-4df2-aa99-2df168573493)

**Comment by stjernando** [comment]
_Kunne vi laget noe av det samme? Altså et API som sender produktet rett inn på plattformen vår etter at det er kjøpt på nett som gjør at det ligger klart til å bli anmeldt neste gang du går inn på Mamon_ @SMadland 

Ikke noe jeg bare kan mekke og selge til XXL uten at XXL allerede slipper meg inn. Det virker som om det er sånn her det funker.

1. Du må være medlem i kundeklubben til Anton Sport og registrert med telefonnummer.
2. Anton Sport gir Tings tilgang til Anton Sport sine kunder via telefonnummeret. 
3. Tings henter info om hva du har kjøpt hos Anton Sport.

😺 

Vi kan gjøre akkurat det samme som Tings gjør, men ikke noe jeg kan preppe på forhånd. Bedriftene i Norge sender jo automagisk en mail til kunden etter et kjøp og spør om de vil rangere produktet de har kjøpt. Også vises den anmeldelsen etterpå. 

Så kan man jo høre om heller vi kan bli med på den reisen eller ta den helt over for vår del. Siden kjernen er at jeg ikke bryr meg om hva Dj broiler synes Nintendo Switch, men hva du synes om den. 
Ei heller bryr jeg meg om hva de botsa på trustpilot sier.

**Comment by SMadland** [comment]
@stjernando Skjønner. Da kan jeg ta det samtidig som jeg møter ulike bedrifter for å få de som kunder på plattformen. Men det er ikke noe spesielt vi/de må gjøre for at det skal fungere greit? Vi får tilgang til kundene og sender kjøpene direkte til vår plattform? Så enkelt og greit 😍

Jeg tenker uansett at det på sikt er en gull måte å gjøre det på. At man kan gå inn på Mamon og finne kjøp man har gjort som ligger klart til å anmeldes. Litt enklere enn å måtte søke opp riktig produkt på riktig nettside for å lage anmeldelsen selv. Og mye mer aktuelt å gjøre det der, når jeg uansett skal inn å sjekke andres anmeldelser og kommentere/like deres kjøp, enn å gidde å bruke tid på å svare en "random" anmeldelse for IKEA.
