### ISSUE TITLE
Visning på toppen av siden

### ISSUE THREAD

**Issue by SMadland** [Mamon-AS/Mamon#82]
Diverse "små" design tanker på på topplinjen. Hentet igjen inpso fra LI.

- Søkefeltet kan gjøres litt mindre - Nå går det over hele skjermen.
- Profil-figur som kan ta deg litt profilen
- Anmeldelse-figur som lar deg lage anmeldelse.
- Mitt nettverk-figur som tar deg til dine venner/nettverk

Da trenger vi kanskje ikke den "sidebaren" heller?

![Image](https://github.com/Mamon-AS/Mamon/assets/118986568/a4ef4335-8eac-4d5f-94cf-6f1f4353d461)

**Comment by stjernando** [comment]
![image](https://github.com/Mamon-AS/Mamon/assets/44195327/7e50d326-3e71-40ad-b00e-c4b3e0db9c41)

**Comment by stjernando** [comment]
Neida, for lite navigering/info så er ikoner i headeren "bedre" enn hamburger. Øyet ditt foretrekker å lete etter info på venstresiden når du skummer en ukjent nettside. Det er ikke et fasitsvar på hva som er best, da det er motargumenter for alle fordeler og ulemper til hamburger/ikoner/venstre/høyre/toppen. 

Det meste jeg gjør er mobile-first og søkefeltet ser dødsnice ut på mobil 😝

**Comment by SMadland** [comment]
Haha, god quote!

Jeg tenker mobile first er gull, støttes 100 %.

De ikonene er like mye for å gjøre siden mer levende. Jeg er glad for alt jeg slipper å "lete" etter. Eksempelvis hvor jeg finner egen profil.

Kan vi ha begge deler? Eller er det klønete?

**Comment by SMadland** [comment]
Søkefeltet kan vi ha som det er om det ser bra ut på mobil. Jeg sjekker nesten bare Mamon på PC 😅

**Comment by stjernando** [comment]
Neida, det kan fikses - jeg bare sier at noen ganger ser det ut som det gjør fordi jeg har bare tenkt mobil 😅

**Comment by SMadland** [comment]
Men fint du sier det, for jeg må sjekke det på mobil oftere. Er der folk kommer til å sjekke Mamon mest.

Og søkefelt ser smashing ut på tlf 🎯💯
